name: ci
on: push
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Switch Xcode to latest version
        run: xcversion select latest
      - name: Generate Xcode project file
        run: swift package generate-xcodeproj
      - name: Build
        run: xcodebuild -scheme SQLite-Package -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.1'
      - name: Test
        run: xcodebuild -scheme SQLite-Package -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.1' test | xcpretty
